name: ENV Variables
# 1. Environment variables can be created at workflow level, job level, step level
# 2. pass environment variables through secrets defined in Github repo settings
# 3. update random.txt and push to the browser
on: push
env: 
  WF_ENV: Available to all jobs
  WF_ENV_SECRET: ${{secrets.WF_ENV}}
jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: Available to all steps in log-env job
    steps:
      - name: Log Env Variables
        env:
          STEP_ENV: Available to only this step
        run:  |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "WF_SECRETS_ENV: ${WF_ENV_SECRET}"
      - name: Log Env 2
        run:  |
          echo "WF_ENV: ${WF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  log-default-env:
    runs-on: ubuntu-latest
    steps:
      - name: Log Env Variables
        env:
          STEP_ENV: Available to only this step
        run:  |
          echo "WF_ENV: ${EF_ENV}"
          echo "JOB_ENV ${JOB_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
  create_issue:
    runs-on: ubuntu-latest 
    permissions:
      issues: write 
      contents: write
    steps:
      - name: 2. Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
      - name: Push a random file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          git add -A
          git commit -m"Random file"
          git push







  

        