name: Context testing  #1. Context https://docs.github.com/en/actions/learn-github-actions/contexts

on: push

jobs:
  functions:
    runs-on: ubuntu-latest
    steps:
      - name: Functions #2. Functions ttps://docs.github.com/en/actions/learn-github-actions/expressions#functions
        run: |
          echo ${{ contains( 'hello','ll') }}
          echo ${{ format('Hello {0} {1} {2}', 'World','!','!') }}
  on_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: runs on push
        run: echo 'This runs on only push'
  fallback_job:
      runs-on: ubuntu-latest
      steps:
        - name: Fail the job
          run: eecho
        - name: fallback job
          if: failure()
          run: echo 'Its a fallback'
        - name: skipp job
          run: echo 'Should not echo this string'
        - name: always run job
          if: always()
          run: echo 'this should run always'

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'