name: Strategy and Matrix # Which is used for multiple environments

on: [push]

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Node node version
        run: node -v 
  node-version-matrix:
    strategy:
      matrix:
        os: [windows-latest,macos-latest,ubuntu-latest]
        node-version: [6,8,10] # an array of options 
      max-parallel: 2 # number of jobs running in parallel
      fail-fast: true
    runs-on: ${{matrix.os}}
    steps:
      - name: Log Node node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
      - name: Log Node node version
        run: node -v 