name: Strategy and Matrix # Which is used for multiple environments

on: [push]

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Node node version
        run: node -v 
  node-version-matrix:
    strategy:
      matrix:
        os: [windows-latest,macos-latest,ubuntu-latest]
        node-version: [6,8,10] # an array of options 
        include: # used to modify any existing combination or can add new combination
          - os: ubuntu-latest
            node-version: 14
          - os: ubuntu-latest
            node-version: 10
            is_ubuntu_10: true
        exclude:  #used to exclude any combination
          - os: ubuntu-latest
            node-version: 8
          - os: macos-latest
            node-version: 8
      max-parallel: 2 # number of jobs running in parallel
      fail-fast: true
      
    runs-on: ${{matrix.os}}
    env:
      IS_UBUNTU_10: ${{ matrix.is_ubuntu_10}}
    steps:
      - name: Log Node node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node_version}}
      - name: Log Node node version
        run: node -v 
      - name: env variables
        run: echo $IS_UBUNTU_10