name: Strategy and Matrix # Which is used for multiple environments

on: [push]

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log Node node version
        run: node -v 
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Log Node node version
        run: node -v     