name: Actions WorkFlow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Sipmle Javascript Action
        id: greet #3. ID to a step, helps to refer in other steps
        uses: actions/hello-world-javascript-action@v1 # 1.actions from github repository
        with:
          who-to-greet: John   #2. input to action
      - name: Log Greeting Time
        run: echo  "${{steps.greet.outputs.time}}" # 3. refering outputs
    
      - name: Checkout
        uses: actions/checkout@v1 #4.Checkout action- it simplifiles checkouting current repositlry
      - name: List Files & Enviornement #verify env variables
        run: |
          pwd
          ls -a  
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"

