name: Shell Commands

on: [push]


jobs: #Simple job
  run-shell-command: # 
    runs-on: ubuntu-latest  
    steps:
      - name: echo a String  # Single line command as a step
        run: echo "Hello World"
        shell: bash # optional if not provided uses default shell.
      - name: Multiline script # Multiple line command as a step
        run: |
          node -v
          npm -v
      - name: python command # using different shell
        run: |
          import platform
          print(platform.processor())
        shell: python
      